# cluster-config.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: math-service-cluster # Name of your EKS cluster
  region: eu-west-2 # Choose your AWS region (e.g., eu-west-2)

nodeGroups:
  - name: math-service-ng # Name of the node group
    instanceType: t3.medium # Or t3.large, depending on your region's availability/cost.
                            # Make sure it can handle 1 CPU & 2GiB per pod, and at least 2 nodes.
    desiredCapacity: 2      # Start with 2 worker nodes
    minSize: 1
    maxSize: 3              # Allow for scaling up nodes if needed, though HPA scales pods.
    # Associate a public IP to instances if they are in public subnets (default for eksctl)
    # If using private subnets, you might need more advanced networking setup.
    # ssh:
    #   allow: true
    #   publicKeyPath: ~/.ssh/id_rsa.pub # Optional: if you want SSH access to nodes