# cluster-config.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: math-service-cluster
  region: eu-west-2
  version: "1.29" # Ensure this matches your desired K8s version
managedNodeGroups:
- name: standard-workers
  instanceType: t3.large # CHANGED FROM t3.medium
  desiredCapacity: 2
  minSize: 2
  maxSize: 3
  volumeSize: 20
  labels: {role: worker}
  tags:
    nodegroup-type: standard