# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: math-service-service
spec:
  selector:
    app: math-service # Selects pods with the label 'app: math-service'
  ports:
    - protocol: TCP
      port: 80        # The port the service will expose (e.g., LoadBalancer listens on 80)
      targetPort: 8000 # The port the container is listening on
  type: LoadBalancer    # This will provision an AWS Load Balancer